// src/App.tsx
import { getCurrentWindow } from "@tauri-apps/api/window";
import { listen } from "@tauri-apps/api/event";
import { enable as enableAutostart, disable as disableAutostart } from "@tauri-apps/plugin-autostart";
import { register, unregisterAll } from "@tauri-apps/plugin-global-shortcut";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  api,
  chooseExternalTextFile,
  chooseMarkdownExport,
  chooseMarkdownImport,
  getErrorMessage,
} from "./api";
import { MarkdownPreview } from "./MarkdownPreview";
import { SettingsPanel } from "./SettingsPanel";
import { Tile } from "./Tile";
import type { AppConfig, ExternalFile, Note, NoteMetadata, ViewMode } from "./types";
import {
  applyTheme,
  countChars,
  filterNotes,
  formatShortDate,
  formatTime,
  groupNotes,
  insertMarkdown,
  metadataFromNote,
  normalizeViewMode,
  noteTitle,
  safeMarkdownFileName,
} from "./utils";

const toolbar = [
  ["bold", "B", "粗体"],
  ["italic", "I", "斜体"],
  ["heading", "H", "标题"],
  ["hr", "—", "分割线"],
  ["ul", "•", "无序列表"],
  ["ol", "1.", "有序列表"],
  ["code", "<>", "代码"],
  ["quote", "❝", "引用"],
  ["inlineMath", "Σ", "行内公式"],
  ["blockMath", "∫", "块级公式"],
] as const;

function currentSurface() {
  const params = new URLSearchParams(window.location.search);
  return {
    surface: params.get("surface") ?? "main",
    id: params.get("id") ?? "",
  };
}

export function App() {
  const { surface, id } = currentSurface();
  if (surface === "pad") return <NotePad />;
  if (surface === "tile") return <TileWindow noteId={id} />;
  return <MainWindow />;
}

function MainWindow() {
  const [config, setConfig] = useState<AppConfig | null>(null);
  const [notes, setNotes] = useState<NoteMetadata[]>([]);
  const [categories, setCategories] = useState<string[]>([]);
  const [externalFiles, setExternalFiles] = useState<ExternalFile[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [query, setQuery] = useState("");
  const [viewMode, setViewMode] = useState<ViewMode>("split");
  const [saveState, setSaveState] = useState<"idle" | "dirty" | "saving" | "saved" | "error">(
    "idle",
  );
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [collapsed, setCollapsed] = useState<Set<string>>(new Set());
  const [activeCategory, setActiveCategory] = useState("");
  const [newCategory, setNewCategory] = useState("");
  const [error, setError] = useState("");
  const textRef = useRef<HTMLTextAreaElement>(null);

  const selectedNote = useMemo(
    () => notes.find((note) => note.id === selectedId) ?? null,
    [notes, selectedId],
  );
  const selectedExternal = useMemo(
    () => externalFiles.find((file) => file.id === selectedId) ?? null,
    [externalFiles, selectedId],
  );
  const filtered = useMemo(() => filterNotes(notes, query), [notes, query]);
  const grouped = useMemo(() => groupNotes(filtered, categories), [filtered, categories]);
  const isExternal = Boolean(selectedExternal);

  const refresh = useCallback(async () => {
    const [nextNotes, nextCategories] = await Promise.all([api.listNotes(), api.listCategories()]);
    setNotes(nextNotes);
    setCategories(nextCategories);
    return nextNotes;
  }, []);

  const loadNote = useCallback(async (noteId: string) => {
    const note = await api.getNote(noteId);
    setSelectedId(note.id);
    setTitle(note.title);
    setContent(note.content);
    setSaveState("saved");
    setError("");
  }, []);

  useEffect(() => {
    // Initial bootstrap loads config, note index, categories, and opens the latest note.
    void (async () => {
      try {
        const [loadedConfig, loadedNotes, loadedCategories] = await Promise.all([
          api.getConfig(),
          api.listNotes(),
          api.listCategories(),
        ]);
        setConfig(loadedConfig);
        applyTheme(loadedConfig.theme);
        setViewMode(normalizeViewMode(loadedConfig.defaultViewMode));
        setNotes(loadedNotes);
        setCategories(loadedCategories);
        setCollapsed(new Set(loadedCategories));
        if (loadedNotes[0]) await loadNote(loadedNotes[0].id);
      } catch (err) {
        setError(getErrorMessage(err));
      }
    })();
    const unlisten = listen("notes-changed", () => void refresh());
    return () => {
      void unlisten.then((fn) => fn());
    };
  }, [loadNote, refresh]);

  useEffect(() => {
    if (!config) return;
    // Re-register shortcuts whenever the user changes either shortcut string in settings.
    void (async () => {
      try {
        await unregisterAll();
        const quick = normalizeShortcut(config.globalShortcut);
        const toggle = normalizeShortcut(config.toggleVisibilityShortcut);
        if (quick) await register(quick, () => void api.openNotepadWindow());
        if (toggle) await register(toggle, () => void api.toggleMainWindow());
      } catch (err) {
        setError(`快捷键注册失败：${getErrorMessage(err)}`);
      }
    })();
    return () => {
      void unregisterAll();
    };
  }, [config?.globalShortcut, config?.toggleVisibilityShortcut]);

  useEffect(() => {
    // Main-window autosave is intentionally debounced to avoid rewriting on every keystroke.
    if (!config?.noteAutoSave || saveState !== "dirty" || isExternal) return;
    const timer = window.setTimeout(() => void saveCurrent(), 800);
    return () => window.clearTimeout(timer);
  }, [content, title, config?.noteAutoSave, saveState, isExternal]);

  useEffect(() => {
    // External files use a separate autosave flag because edits write back to arbitrary paths.
    if (!config?.externalFileAutoSave || saveState !== "dirty" || !selectedExternal) return;
    const timer = window.setTimeout(() => void saveCurrent(), 800);
    return () => window.clearTimeout(timer);
  }, [content, title, config?.externalFileAutoSave, saveState, selectedExternal]);

  async function createBlank() {
    const note = await api.createNote({ title: "无标题笔记", content: "", category: activeCategory });
    setNotes((current) => [metadataFromNote(note), ...current]);
    await loadNote(note.id);
  }

  async function saveCurrent() {
    if (!selectedId) return;
    setSaveState("saving");
    try {
      // External documents are not imported unless the user chooses import; save back in place.
      if (selectedExternal) {
        await api.saveExternalFile(selectedExternal.filePath, content);
        setSaveState("saved");
        return;
      }
      const category = selectedNote?.category ?? activeCategory;
      const note = await api.updateNote(selectedId, { title, content, category });
      setNotes((current) =>
        [metadataFromNote(note), ...current.filter((item) => item.id !== note.id)].sort((a, b) =>
          b.updatedAt.localeCompare(a.updatedAt),
        ),
      );
      setSaveState("saved");
    } catch (err) {
      setSaveState("error");
      setError(getErrorMessage(err));
    }
  }

  async function deleteCurrent() {
    if (!selectedId || selectedExternal) return;
    await api.deleteNote(selectedId);
    const next = await refresh();
    if (next[0]) await loadNote(next[0].id);
    else {
      setSelectedId(null);
      setTitle("");
      setContent("");
      setSaveState("idle");
    }
  }

  async function importMarkdown() {
    const path = await chooseMarkdownImport();
    if (!path) return;
    const note = await api.importMarkdown(path, activeCategory);
    await refresh();
    await loadNote(note.id);
  }

  async function exportMarkdown() {
    if (!selectedId || selectedExternal) return;
    const path = await chooseMarkdownExport(safeMarkdownFileName(title));
    if (path) await api.exportMarkdown(selectedId, path);
  }

  async function openExternal() {
    const path = await chooseExternalTextFile();
    if (!path) return;
    const fileName = path.split(/[\\/]/).pop() ?? path;
    const content = await api.readExternalFile(path);
    const external = { id: path, title: fileName.replace(/\.(md|txt)$/i, ""), filePath: path };
    setExternalFiles((current) =>
      current.some((item) => item.id === path) ? current : [...current, external],
    );
    setSelectedId(path);
    setTitle(external.title);
    setContent(content);
    setSaveState("saved");
  }

  async function saveSettings(next: AppConfig) {
    setConfig(next);
    applyTheme(next.theme);
    try {
      // The Tauri autostart plugin owns OS registration; config persistence records the UI state.
      if (next.autostart) await enableAutostart();
      else await disableAutostart();
    } catch (err) {
      setError(`开机自启设置失败：${getErrorMessage(err)}`);
    }
    const saved = await api.saveConfig(next);
    setConfig(saved);
  }

  function applyFormat(action: string) {
    const textarea = textRef.current;
    if (!textarea) return;
    // Markdown toolbar preserves selection so users can immediately overwrite placeholder text.
    const result = insertMarkdown(content, textarea.selectionStart, textarea.selectionEnd, action);
    setContent(result.value);
    setSaveState("dirty");
    requestAnimationFrame(() => {
      textarea.focus();
      textarea.setSelectionRange(result.start, result.end);
    });
  }

  async function addCategory() {
    const value = newCategory.trim();
    if (!value) return;
    setCategories(await api.createCategory(value));
    setNewCategory("");
  }

  async function moveSelected(category: string) {
    if (!selectedId || selectedExternal) return;
    const note = await api.moveNoteCategory(selectedId, category);
    setActiveCategory(category);
    setNotes((current) => current.map((item) => (item.id === note.id ? metadataFromNote(note) : item)));
  }

  if (!config) return <div className="boot">正在启动花笺...</div>;

  return (
    <div className="app-shell">
      {config.backgroundImagePath && (
        <div
          className="background-layer"
          style={{
            backgroundImage: `url("${config.backgroundImagePath}")`,
            backgroundSize: config.backgroundFit === "repeat" ? "auto" : config.backgroundFit,
            backgroundRepeat: config.backgroundFit === "repeat" ? "repeat" : "no-repeat",
            backgroundPosition: `${config.backgroundPositionX}% ${config.backgroundPositionY}%`,
            filter: `blur(${config.backgroundBlur}px) scale(${config.backgroundScale})`,
          }}
        />
      )}
      <div className="background-dim" style={{ opacity: config.backgroundDim }} />
      <aside className="sidebar">
        <div className="window-bar" data-tauri-drag-region>
          <strong>花笺</strong>
          <div>
            <button onClick={() => void api.openNotepadWindow()} title="快捷便签">
              ＋
            </button>
            <button onClick={() => setSettingsOpen(true)} title="设置">
              ⚙
            </button>
          </div>
        </div>
        <div className="sidebar-actions">
          <button onClick={() => void createBlank()}>新建</button>
          <button onClick={() => void importMarkdown()}>导入</button>
          <button onClick={() => void openExternal()}>外部</button>
        </div>
        <input
          className="search"
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder="搜索笔记、内容或分类"
        />
        <div className="category-create">
          <input
            value={newCategory}
            onChange={(event) => setNewCategory(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter") void addCategory();
            }}
            placeholder="新增分类"
          />
          <button onClick={() => void addCategory()}>+</button>
        </div>
        <div className="note-list">
          {grouped.map(([category, items]) => (
            <section key={category || "none"} className="category-block">
              <button
                className="category-title"
                onClick={() =>
                  setCollapsed((current) => {
                    const next = new Set(current);
                    next.has(category) ? next.delete(category) : next.add(category);
                    return next;
                  })
                }
              >
                <span>{category || "未分类"}</span>
                <b>{items.length}</b>
              </button>
              {!collapsed.has(category) &&
                items.map((note) => (
                  <button
                    key={note.id}
                    className={`note-item ${selectedId === note.id ? "selected" : ""}`}
                    onClick={() => void loadNote(note.id)}
                    onContextMenu={(event) => {
                      event.preventDefault();
                      void moveSelected(category);
                    }}
                  >
                    <strong>{noteTitle(note)}</strong>
                    <span>{note.preview || "空白笔记"}</span>
                    <small>
                      {formatShortDate(note.updatedAt)} · {note.wordCount} 字
                    </small>
                  </button>
                ))}
            </section>
          ))}
          {externalFiles.map((file) => (
            <button
              key={file.id}
              className={`note-item external ${selectedId === file.id ? "selected" : ""}`}
              onClick={async () => {
                setSelectedId(file.id);
                setTitle(file.title);
                setContent(await api.readExternalFile(file.filePath));
                setSaveState("saved");
              }}
            >
              <strong>{file.title}</strong>
              <span>{file.filePath}</span>
              <small>外部文件</small>
            </button>
          ))}
        </div>
      </aside>
      <main className="editor-shell">
        <header className="titlebar" data-tauri-drag-region>
          <div className="titlebar-title">Windows 现代便签系统</div>
          <div className="titlebar-actions">
            <button onClick={() => void getCurrentWindow().minimize()}>−</button>
            <button onClick={() => void getCurrentWindow().toggleMaximize()}>□</button>
            <button
              onClick={() =>
                config.closeToTray ? void getCurrentWindow().hide() : void getCurrentWindow().close()
              }
            >
              ×
            </button>
          </div>
        </header>
        {error && <div className="error-banner">{error}</div>}
        <div className="editor-toolbar">
          <button onClick={() => void saveCurrent()} disabled={!selectedId}>
            保存
          </button>
          <button onClick={() => void exportMarkdown()} disabled={!selectedId || isExternal}>
            导出
          </button>
          <button onClick={() => void deleteCurrent()} disabled={!selectedId || isExternal}>
            删除
          </button>
          <button
            onClick={() => selectedId && void api.openTileWindow(selectedId)}
            disabled={!selectedId || isExternal}
          >
            钉到屏幕
          </button>
          <select value={activeCategory} onChange={(event) => void moveSelected(event.target.value)}>
            <option value="">未分类</option>
            {categories.map((category) => (
              <option key={category} value={category}>
                {category}
              </option>
            ))}
          </select>
          <div className="format-buttons">
            {toolbar.map(([action, label, tip]) => (
              <button key={action} title={tip} onClick={() => applyFormat(action)}>
                {label}
              </button>
            ))}
          </div>
          <div className="segmented mode-tabs">
            {(["edit", "split", "preview"] as ViewMode[]).map((mode) => (
              <button
                key={mode}
                className={viewMode === mode ? "active" : ""}
                onClick={() => setViewMode(mode)}
              >
                {mode === "edit" ? "编辑" : mode === "split" ? "分栏" : "预览"}
              </button>
            ))}
          </div>
        </div>
        <div className="editor-meta">
          <input
            value={title}
            disabled={!selectedId}
            onChange={(event) => {
              setTitle(event.target.value);
              setSaveState("dirty");
            }}
            placeholder="无标题笔记"
          />
          <span>
            {selectedExternal
              ? `外部文件 · ${selectedExternal.filePath}`
              : selectedNote
                ? `${formatShortDate(selectedNote.updatedAt)} ${formatTime(selectedNote.updatedAt)}`
                : "选择或新建一篇笔记"}
          </span>
          <span>{countChars(content)} 字</span>
          <span className={`save-state ${saveState}`}>{saveState}</span>
        </div>
        <div className={`workspace ${viewMode}`}>
          {(viewMode === "edit" || viewMode === "split") && (
            <textarea
              ref={textRef}
              value={content}
              disabled={!selectedId}
              onChange={(event) => {
                setContent(event.target.value);
                setSaveState("dirty");
              }}
              style={{ fontSize: config.fontSize, tabSize: config.tabIndentSize }}
              placeholder="开始写作……"
            />
          )}
          {(viewMode === "preview" || viewMode === "split") && (
            <div className="preview-pane">
              <MarkdownPreview
                content={content}
                fontSize={config.fontSize}
                renderHtml={config.renderHtmlMarkdown}
              />
            </div>
          )}
        </div>
        <footer className="statusbar">
          <span>Ln {content.split("\n").length}</span>
          <span>Markdown + LaTeX</span>
          <span>UTF-8</span>
          <span>{(new TextEncoder().encode(content).length / 1024).toFixed(1)} KB</span>
        </footer>
      </main>
      {settingsOpen && (
        <SettingsPanel config={config} onChange={(next) => void saveSettings(next)} onClose={() => setSettingsOpen(false)} />
      )}
    </div>
  );
}

function normalizeShortcut(value: string): string {
  // Settings use friendly labels; the plugin expects CommandOrControl for cross-platform Ctrl/Cmd.
  return value
    .trim()
    .replace(/\s+/g, "")
    .replace(/^Ctrl\+/i, "CommandOrControl+")
    .replace(/\+Ctrl\+/i, "+CommandOrControl+")
    .replace(/Alt/i, "Alt")
    .replace(/Shift/i, "Shift");
}

function NotePad() {
  const [config, setConfig] = useState<AppConfig | null>(null);
  const [notes, setNotes] = useState<NoteMetadata[]>([]);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [openList, setOpenList] = useState(false);
  const [status, setStatus] = useState("空");

  useEffect(() => {
    // Shortcut pads load only the light data needed for quick open and note creation.
    void Promise.all([api.getConfig(), api.listNotes()]).then(([c, n]) => {
      setConfig(c);
      setNotes(n);
    });
  }, []);

  useEffect(() => {
    // Pad autosave mirrors the original app's "write and close quickly" workflow.
    if (!config?.noteSurfaceAutoSave || status !== "未保存") return;
    const timer = window.setTimeout(() => void save(), 900);
    return () => window.clearTimeout(timer);
  }, [content, title, config?.noteSurfaceAutoSave, status]);

  async function save() {
    const request = { title, content, category: "" };
    const note = editingId ? await api.updateNote(editingId, request) : await api.createNote(request);
    setEditingId(note.id);
    setNotes((current) => [metadataFromNote(note), ...current.filter((item) => item.id !== note.id)]);
    setStatus("已保存");
  }

  async function open(noteId: string) {
    const note = await api.getNote(noteId);
    setEditingId(note.id);
    setTitle(note.title);
    setContent(note.content);
    setOpenList(false);
    setStatus("已打开");
  }

  if (!config) return <div className="boot">正在打开快捷便签...</div>;

  return (
    <div className="pad-shell">
      <header data-tauri-drag-region>
        <div>
          <button className={!openList ? "active" : ""} onClick={() => setOpenList(false)}>
            {editingId ? "编辑" : "新建"}
          </button>
          <button className={openList ? "active" : ""} onClick={() => setOpenList(true)}>
            打开
          </button>
        </div>
        <div>
          <button disabled={!editingId} onClick={() => editingId && void api.openTileWindow(editingId)}>
            📌
          </button>
          <button onClick={() => void getCurrentWindow().close()}>×</button>
        </div>
      </header>
      {openList ? (
        <div className="pad-list">
          {notes.map((note) => (
            <button key={note.id} onClick={() => void open(note.id)}>
              <strong>{noteTitle(note)}</strong>
              <span>{note.preview || "空白笔记"}</span>
            </button>
          ))}
        </div>
      ) : (
        <div className="pad-editor">
          <input
            value={title}
            onChange={(event) => {
              setTitle(event.target.value);
              setStatus("未保存");
            }}
            placeholder="标题（可选）"
            style={{ fontSize: config.surfaceFontSize }}
          />
          <textarea
            value={content}
            onChange={(event) => {
              setContent(event.target.value);
              setStatus("未保存");
            }}
            placeholder="写点什么……"
            style={{ fontSize: config.surfaceFontSize, tabSize: config.tabIndentSize }}
          />
          <footer>
            <span>
              {countChars(content)} 字 · {status}
            </span>
            <button onClick={() => {
              setEditingId(null);
              setTitle("");
              setContent("");
              setStatus("空");
            }}>
              清空
            </button>
            <button onClick={() => void save()}>保存</button>
          </footer>
        </div>
      )}
    </div>
  );
}

function TileWindow({ noteId }: { noteId: string }) {
  const [note, setNote] = useState<Note | null>(null);
  const [config, setConfig] = useState<AppConfig | null>(null);
  useEffect(() => {
    // Tile windows are read-focused; edits happen by reopening a pad or the main editor.
    void Promise.all([api.getConfig(), api.getNote(noteId)]).then(([c, n]) => {
      setConfig(c);
      setNote(n);
    });
  }, [noteId]);
  if (!note || !config) return <div className="boot">正在打开磁贴...</div>;
  return (
    <Tile
      title={note.title}
      content={note.content}
      color={config.tileColorMode === "custom" ? config.tileColor : "#f8f5ec"}
      fontSize={config.surfaceFontSize}
      renderMarkdown={config.tileRenderMarkdown}
      onCopy={() => void navigator.clipboard.writeText(note.content)}
      onEdit={() => void api.openNotepadWindow()}
      onClose={() => void getCurrentWindow().close()}
    />
  );
}

// src/App.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from "vue";
import {
  appWindow,
  api,
  chooseExternalTextFile,
  chooseMarkdownExport,
  chooseMarkdownImport,
  getErrorMessage,
  listen,
} from "./api";
import MarkdownPreview from "./MarkdownPreview.vue";
import SettingsPanel from "./SettingsPanel.vue";
import Tile from "./Tile.vue";
import type { AppConfig, ExternalFile, Note, NoteMetadata, ViewMode } from "./types";
import {
  applyTheme,
  countChars,
  filterNotes,
  formatShortDate,
  formatTime,
  groupNotes,
  insertMarkdown,
  metadataFromNote,
  normalizeViewMode,
  noteTitle,
  safeMarkdownFileName,
} from "./utils";

const toolbar = [
  ["bold", "B", "粗体"],
  ["italic", "I", "斜体"],
  ["heading", "H", "标题"],
  ["hr", "-", "分割线"],
  ["ul", "•", "无序列表"],
  ["ol", "1.", "有序列表"],
  ["code", "<>", "代码"],
  ["quote", "❝", "引用"],
  ["inlineMath", "Σ", "行内公式"],
  ["blockMath", "∫", "块级公式"],
] as const;

const TODO_MARKER = "[[desktop-note:todo]]";

function currentSurface() {
  const params = new URLSearchParams(window.location.search);
  return {
    surface: params.get("surface") ?? "main",
    id: params.get("id") ?? "",
  };
}

const { surface, id } = currentSurface();

const config = ref<AppConfig | null>(null);
const notes = ref<NoteMetadata[]>([]);
const categories = ref<string[]>([]);
const externalFiles = ref<ExternalFile[]>([]);
const selectedId = ref<string | null>(null);
const title = ref("");
const content = ref("");
const query = ref("");
const viewMode = ref<ViewMode>("split");
const saveState = ref<"idle" | "dirty" | "saving" | "saved" | "error">("idle");
const settingsOpen = ref(false);
const createMenuOpen = ref(false);
const categoryCreateOpen = ref(false);
const collapsed = ref<Set<string>>(new Set());
const activeCategory = ref("");
const newCategory = ref("");
const error = ref("");
const textRef = ref<HTMLTextAreaElement | null>(null);
const swipedItem = ref("");
const swipeStart = ref<{ key: string; x: number; y: number } | null>(null);
const suppressSwipeClickUntil = ref(0);
const openList = ref(false);
const status = ref("空");
const editingId = ref<string | null>(null);
const tileNote = ref<Note | null>(null);
const tileEditing = ref(true);
const tileFixed = ref(false);
const tileStatus = ref<"saved" | "dirty" | "saving" | "error">("saved");

const isMain = computed(() => surface === "main");
const isPad = computed(() => surface === "pad");
const isTile = computed(() => surface === "tile");
const selectedNote = computed(() => notes.value.find((note) => note.id === selectedId.value) ?? null);
const selectedExternal = computed(
  () => externalFiles.value.find((file) => file.id === selectedId.value) ?? null,
);
const filtered = computed(() => filterNotes(notes.value, query.value));
const grouped = computed(() => groupNotes(filtered.value, categories.value));
const isExternal = computed(() => Boolean(selectedExternal.value));
const isTodoNote = computed(() => content.value.startsWith(TODO_MARKER));
const todoItems = computed(() => {
  if (!isTodoNote.value) return [];
  const raw = content.value.slice(TODO_MARKER.length).replace(/^\r?\n/, "");
  const lines = raw.split(/\r?\n/);
  const items = lines.map((line) => {
    const match = /^\[([ xX])\]\s?(.*)$/.exec(line);
    return {
      done: match ? match[1].toLowerCase() === "x" : false,
      text: match ? match[2] : line,
    };
  });
  return items.length ? items : [{ done: false, text: "" }];
});

async function refresh() {
  const [nextNotes, nextCategories] = await Promise.all([api.listNotes(), api.listCategories()]);
  notes.value = nextNotes;
  categories.value = nextCategories;
  return nextNotes;
}

async function loadNote(noteId: string) {
  const note = await api.getNote(noteId);
  selectedId.value = note.id;
  title.value = note.title;
  content.value = note.content;
  saveState.value = "saved";
  error.value = "";
}

async function bootstrapMain() {
  try {
    const [loadedConfig, loadedNotes, loadedCategories] = await Promise.all([
      api.getConfig(),
      api.listNotes(),
      api.listCategories(),
    ]);
    config.value = loadedConfig;
    applyTheme(loadedConfig.theme);
    viewMode.value = normalizeViewMode(loadedConfig.defaultViewMode);
    notes.value = loadedNotes;
    categories.value = loadedCategories;
    collapsed.value = new Set(loadedCategories);
    if (loadedNotes[0]) await loadNote(loadedNotes[0].id);
  } catch (err) {
    error.value = getErrorMessage(err);
  }
}

async function bootstrapPad() {
  const [loadedConfig, loadedNotes] = await Promise.all([api.getConfig(), api.listNotes()]);
  config.value = loadedConfig;
  notes.value = loadedNotes;
}

async function bootstrapTile() {
  const [loadedConfig, note] = await Promise.all([api.getConfig(), api.getNote(id)]);
  config.value = loadedConfig;
  tileNote.value = note;
  tileStatus.value = "saved";
}

onMounted(() => {
  if (isMain.value) void bootstrapMain();
  if (isPad.value) void bootstrapPad();
  if (isTile.value) void bootstrapTile();
});

if (isMain.value) {
  const stop = ref<(() => void) | null>(null);
  onMounted(async () => {
    stop.value = await listen("notes-changed", () => void refresh());
  });
  onUnmounted(() => {
    stop.value?.();
  });
}

watch([content, title, saveState], () => {
  if (!config.value?.noteAutoSave || saveState.value !== "dirty" || isExternal.value || !isMain.value) return;
  window.setTimeout(() => void saveCurrent(), 800);
});

watch([content, title, saveState, selectedExternal], () => {
  if (!config.value?.externalFileAutoSave || saveState.value !== "dirty" || !selectedExternal.value) return;
  window.setTimeout(() => void saveCurrent(), 800);
});

watch([content, title, status], () => {
  if (!config.value?.noteSurfaceAutoSave || status.value !== "未保存" || !isPad.value) return;
  window.setTimeout(() => void savePad(), 900);
});

watch([() => tileNote.value?.title, () => tileNote.value?.content, tileStatus], () => {
  if (!config.value?.noteSurfaceAutoSave || tileStatus.value !== "dirty" || !isTile.value) return;
  window.setTimeout(() => void saveTileNote(), 900);
});

async function createBlank() {
  const note = await api.createNote({ title: "无标题笔记", content: "", category: activeCategory.value });
  notes.value = [metadataFromNote(note), ...notes.value];
  await loadNote(note.id);
}

async function createTodoNote() {
  const note = await api.createNote({
    title: "待办事项",
    content: `${TODO_MARKER}\n[ ] `,
    category: activeCategory.value,
  });
  notes.value = [metadataFromNote(note), ...notes.value];
  createMenuOpen.value = false;
  await loadNote(note.id);
}

function writeTodoItems(items: Array<{ done: boolean; text: string }>) {
  content.value = `${TODO_MARKER}\n${items.map((item) => `[${item.done ? "x" : " "}] ${item.text}`).join("\n")}`;
  saveState.value = "dirty";
}

function updateTodoText(index: number, value: string) {
  const items = [...todoItems.value];
  items[index] = { ...items[index], text: value };
  writeTodoItems(items);
}

function toggleTodoItem(index: number) {
  const items = [...todoItems.value];
  items[index] = { ...items[index], done: !items[index].done };
  writeTodoItems(items);
}

function addTodoItem(index = todoItems.value.length - 1) {
  const items = [...todoItems.value];
  items.splice(index + 1, 0, { done: false, text: "" });
  writeTodoItems(items);
}

function removeTodoItem(index: number) {
  const items = todoItems.value.filter((_, itemIndex) => itemIndex !== index);
  writeTodoItems(items.length ? items : [{ done: false, text: "" }]);
}

function handleTodoKeydown(event: KeyboardEvent, index: number) {
  if (event.key === "Enter") {
    event.preventDefault();
    addTodoItem(index);
    void nextTick(() => {
      const nextInput = document.querySelector<HTMLInputElement>(`[data-todo-index="${index + 1}"]`);
      nextInput?.focus();
    });
    return;
  }
  if (event.key === "Backspace" && !todoItems.value[index]?.text && todoItems.value.length > 1) {
    event.preventDefault();
    removeTodoItem(index);
    void nextTick(() => {
      const previousInput = document.querySelector<HTMLInputElement>(
        `[data-todo-index="${Math.max(0, index - 1)}"]`,
      );
      previousInput?.focus();
    });
  }
}

async function saveCurrent() {
  if (!selectedId.value) return;
  saveState.value = "saving";
  try {
    if (selectedExternal.value) {
      await api.saveExternalFile(selectedExternal.value.filePath, content.value);
      saveState.value = "saved";
      return;
    }
    const category = selectedNote.value?.category ?? activeCategory.value;
    const note = await api.updateNote(selectedId.value, { title: title.value, content: content.value, category });
    notes.value = [metadataFromNote(note), ...notes.value.filter((item) => item.id !== note.id)].sort((a, b) =>
      b.updatedAt.localeCompare(a.updatedAt),
    );
    saveState.value = "saved";
  } catch (err) {
    saveState.value = "error";
    error.value = getErrorMessage(err);
  }
}

async function deleteCurrent() {
  if (!selectedId.value || selectedExternal.value) return;
  await deleteNoteById(selectedId.value);
}

async function deleteNoteById(noteId: string) {
  await api.deleteNote(noteId);
  swipedItem.value = "";
  const next = await refresh();
  if (selectedId.value === noteId && next[0]) await loadNote(next[0].id);
  else if (selectedId.value === noteId) {
    selectedId.value = null;
    title.value = "";
    content.value = "";
    saveState.value = "idle";
  }
}

async function deleteCategoryByName(category: string) {
  if (!category) return;
  categories.value = await api.deleteCategory(category);
  swipedItem.value = "";
  if (activeCategory.value === category) activeCategory.value = "";
  const next = await refresh();
  if (selectedId.value && !next.some((note) => note.id === selectedId.value)) {
    if (next[0]) await loadNote(next[0].id);
    else {
      selectedId.value = null;
      title.value = "";
      content.value = "";
      saveState.value = "idle";
    }
  }
}

function swipeKey(type: "category" | "note", id: string) {
  return `${type}:${id || "none"}`;
}

function startSwipe(event: PointerEvent, key: string) {
  if (key === swipeKey("category", "")) return;
  swipeStart.value = { key, x: event.clientX, y: event.clientY };
}

function moveSwipe(event: PointerEvent) {
  if (!swipeStart.value) return;
  const deltaX = event.clientX - swipeStart.value.x;
  const deltaY = Math.abs(event.clientY - swipeStart.value.y);
  if (deltaX > 34 && deltaY < 26) {
    swipedItem.value = swipeStart.value.key;
    suppressSwipeClickUntil.value = Date.now() + 350;
  }
}

function endSwipe() {
  swipeStart.value = null;
}

function shouldSuppressSwipeClick() {
  return Date.now() < suppressSwipeClickUntil.value;
}

async function openSwipedNote(noteId: string) {
  if (shouldSuppressSwipeClick()) return;
  const key = swipeKey("note", noteId);
  if (swipedItem.value === key) {
    swipedItem.value = "";
    return;
  }
  swipedItem.value = "";
  await loadNote(noteId);
}

function toggleSwipedCategory(category: string) {
  if (shouldSuppressSwipeClick()) return;
  const key = swipeKey("category", category);
  if (swipedItem.value === key) {
    swipedItem.value = "";
    return;
  }
  swipedItem.value = "";
  collapsed.value = collapsed.value.has(category)
    ? new Set([...collapsed.value].filter((item) => item !== category))
    : new Set([...collapsed.value, category]);
}

async function importMarkdown() {
  const path = await chooseMarkdownImport();
  if (!path) return;
  const note = await api.importMarkdown(path, activeCategory.value);
  await refresh();
  await loadNote(note.id);
}

async function exportMarkdown() {
  if (!selectedId.value || selectedExternal.value) return;
  const path = await chooseMarkdownExport(safeMarkdownFileName(title.value));
  if (path) await api.exportMarkdown(selectedId.value, path);
}

async function openExternal() {
  const path = await chooseExternalTextFile();
  if (!path) return;
  const fileName = path.split(/[\\/]/).pop() ?? path;
  const externalContent = await api.readExternalFile(path);
  const external = { id: path, title: fileName.replace(/\.(md|txt)$/i, ""), filePath: path };
  if (!externalFiles.value.some((item) => item.id === path)) externalFiles.value = [...externalFiles.value, external];
  selectedId.value = path;
  title.value = external.title;
  content.value = externalContent;
  saveState.value = "saved";
}

async function saveSettings(next: AppConfig) {
  config.value = next;
  applyTheme(next.theme);
  config.value = await api.saveConfig(next);
}

function applyFormat(action: string) {
  const textarea = textRef.value;
  if (!textarea) return;
  const result = insertMarkdown(content.value, textarea.selectionStart, textarea.selectionEnd, action);
  content.value = result.value;
  saveState.value = "dirty";
  void nextTick(() => {
    textarea.focus();
    textarea.setSelectionRange(result.start, result.end);
  });
}

function toggleTask(index: number) {
  let current = -1;
  const lines = content.value.split("\n");
  const next = lines.map((line) => {
    const match = /^(\s*[-*]\s+\[)([ xX])(\]\s+.*)$/.exec(line);
    if (!match) return line;
    current += 1;
    if (current !== index) return line;
    return `${match[1]}${match[2].toLowerCase() === "x" ? " " : "x"}${match[3]}`;
  });
  content.value = next.join("\n");
  saveState.value = "dirty";
}

function handleEditorKeydown(event: KeyboardEvent) {
  if (event.key !== "Enter" || event.shiftKey || event.ctrlKey || event.altKey || event.metaKey) return;
  const textarea = textRef.value;
  if (!textarea) return;
  const lineStart = content.value.lastIndexOf("\n", textarea.selectionStart - 1) + 1;
  const line = content.value.slice(lineStart, textarea.selectionStart);
  if (!/^\s*[-*]\s+\[[ xX]\]\s+/.test(line)) return;
  event.preventDefault();
  const insert = "\n- [ ] ";
  const start = textarea.selectionStart;
  const end = textarea.selectionEnd;
  content.value = content.value.slice(0, start) + insert + content.value.slice(end);
  saveState.value = "dirty";
  void nextTick(() => {
    textarea.focus();
    textarea.setSelectionRange(start + insert.length, start + insert.length);
  });
}

async function addCategory() {
  const value = newCategory.value.trim();
  if (!value) return;
  categories.value = await api.createCategory(value);
  newCategory.value = "";
  createMenuOpen.value = false;
  categoryCreateOpen.value = false;
}

async function moveSelected(category: string) {
  if (!selectedId.value || selectedExternal.value) return;
  const note = await api.moveNoteCategory(selectedId.value, category);
  activeCategory.value = category;
  notes.value = notes.value.map((item) => (item.id === note.id ? metadataFromNote(note) : item));
}

async function savePad() {
  const request = { title: title.value, content: content.value, category: "" };
  const note = editingId.value ? await api.updateNote(editingId.value, request) : await api.createNote(request);
  editingId.value = note.id;
  notes.value = [metadataFromNote(note), ...notes.value.filter((item) => item.id !== note.id)];
  status.value = "已保存";
}

async function openPadNote(noteId: string) {
  const note = await api.getNote(noteId);
  editingId.value = note.id;
  title.value = note.title;
  content.value = note.content;
  openList.value = false;
  status.value = "已打开";
}

function clearPad() {
  editingId.value = null;
  title.value = "";
  content.value = "";
  status.value = "空";
}

function contentKb(value: string) {
  return (new TextEncoder().encode(value).length / 1024).toFixed(1);
}

async function copyTileContent() {
  if (tileNote.value) await navigator.clipboard.writeText(tileNote.value.content);
}

function updateTileTitle(value: string) {
  if (!tileNote.value) return;
  tileNote.value = { ...tileNote.value, title: value };
  tileStatus.value = "dirty";
}

function updateTileContent(value: string) {
  if (!tileNote.value) return;
  tileNote.value = { ...tileNote.value, content: value };
  tileStatus.value = "dirty";
}

async function saveTileNote() {
  if (!tileNote.value || tileStatus.value === "saving") return;
  tileStatus.value = "saving";
  try {
    tileNote.value = await api.updateNote(tileNote.value.id, {
      title: tileNote.value.title,
      content: tileNote.value.content,
      category: tileNote.value.category,
    });
    tileStatus.value = "saved";
  } catch (err) {
    tileStatus.value = "error";
    error.value = getErrorMessage(err);
  }
}

async function toggleTileFixed() {
  tileFixed.value = !tileFixed.value;
  await appWindow.setAlwaysOnTop(!tileFixed.value);
}
</script>

<template>
  <div v-if="isMain && !config" class="boot">正在启动云笺阁...</div>
  <div v-else-if="isPad && !config" class="boot">正在打开快捷便签...</div>
  <div v-else-if="isTile && (!tileNote || !config)" class="boot">正在打开磁贴...</div>

  <div v-else-if="isMain && config" class="app-shell">
    <div
      v-if="config.backgroundImagePath"
      class="background-layer"
      :style="{
        backgroundImage: `url('${config.backgroundImagePath}')`,
        backgroundSize: config.backgroundFit === 'repeat' ? 'auto' : config.backgroundFit,
        backgroundRepeat: config.backgroundFit === 'repeat' ? 'repeat' : 'no-repeat',
        backgroundPosition: `${config.backgroundPositionX}% ${config.backgroundPositionY}%`,
        filter: `blur(${config.backgroundBlur}px) scale(${config.backgroundScale})`,
      }"
    />
    <div class="background-dim" :style="{ opacity: config.backgroundDim }" />
    <aside class="sidebar">
      <div class="window-bar" data-drag-region>
        <strong>云笺阁</strong>
        <div>
          <button
            title="新建"
            @click="
              createMenuOpen = !createMenuOpen;
              categoryCreateOpen = false;
            "
          >
            ＋
          </button>
          <button title="设置" @click="settingsOpen = true">⚙</button>
        </div>
      </div>
      <div v-if="createMenuOpen" class="create-menu">
        <template v-if="!categoryCreateOpen">
          <button @click="api.openNotepadWindow(); createMenuOpen = false">快捷便签</button>
          <button @click="createTodoNote">待办便签</button>
          <button @click="categoryCreateOpen = true">新增分类</button>
        </template>
        <template v-else>
          <input
            v-model="newCategory"
            placeholder="分类名称"
            autofocus
            @keydown.enter="addCategory"
            @keydown.esc="
              categoryCreateOpen = false;
              newCategory = '';
            "
          />
          <div class="create-menu-actions">
            <button @click="categoryCreateOpen = false; newCategory = ''">取消</button>
            <button @click="addCategory">添加</button>
          </div>
        </template>
      </div>
      <div class="sidebar-actions">
        <button @click="createBlank">新建</button>
        <button @click="importMarkdown">导入</button>
        <button @click="openExternal">外部</button>
      </div>
      <input v-model="query" class="search" placeholder="搜索笔记、内容或分类" />
      <div class="note-list">
        <section v-for="[category, items] in grouped" :key="category || 'none'" class="category-block">
          <div :class="['swipe-row', swipedItem === swipeKey('category', category) ? 'revealed' : '']">
            <button
              v-if="category"
              class="swipe-delete"
              @click="deleteCategoryByName(category)"
            >
              删除
            </button>
            <button
              class="category-title swipe-content"
              @pointerdown="startSwipe($event, swipeKey('category', category))"
              @pointermove="moveSwipe"
              @pointerup="endSwipe"
              @pointercancel="endSwipe"
              @click="toggleSwipedCategory(category)"
            >
              <span>{{ category || "未分类" }}</span>
              <b>{{ items.length }}</b>
            </button>
          </div>
          <template v-if="!collapsed.has(category)">
            <div
              v-for="note in items"
              :key="note.id"
              :class="['swipe-row', 'note-swipe-row', swipedItem === swipeKey('note', note.id) ? 'revealed' : '']"
            >
              <button class="swipe-delete" @click="deleteNoteById(note.id)">删除</button>
              <button
                :class="['note-item', 'swipe-content', selectedId === note.id ? 'selected' : '']"
                @pointerdown="startSwipe($event, swipeKey('note', note.id))"
                @pointermove="moveSwipe"
                @pointerup="endSwipe"
                @pointercancel="endSwipe"
                @click="openSwipedNote(note.id)"
                @contextmenu.prevent="moveSelected(category)"
              >
                <strong>{{ noteTitle(note) }}</strong>
                <span>{{ note.preview || "空白笔记" }}</span>
                <small>{{ formatShortDate(note.updatedAt) }} · {{ note.wordCount }} 字</small>
              </button>
            </div>
          </template>
        </section>
        <button
          v-for="file in externalFiles"
          :key="file.id"
          :class="['note-item', 'external', selectedId === file.id ? 'selected' : '']"
          @click="
            async () => {
              selectedId = file.id;
              title = file.title;
              content = await api.readExternalFile(file.filePath);
              saveState = 'saved';
            }
          "
        >
          <strong>{{ file.title }}</strong>
          <span>{{ file.filePath }}</span>
          <small>外部文件</small>
        </button>
      </div>
    </aside>

    <main class="editor-shell">
      <header class="titlebar" data-drag-region>
        <div class="titlebar-title" aria-hidden="true"></div>
        <div class="titlebar-actions">
          <button @click="appWindow.minimize()">−</button>
          <button @click="appWindow.toggleMaximize()">□</button>
          <button @click="config.closeToTray ? appWindow.hide() : appWindow.close()">×</button>
        </div>
      </header>
      <div v-if="error" class="error-banner">{{ error }}</div>
      <div class="editor-toolbar">
        <button :disabled="!selectedId" @click="saveCurrent">保存</button>
        <button :disabled="!selectedId || isExternal" @click="exportMarkdown">导出</button>
        <button :disabled="!selectedId || isExternal" @click="deleteCurrent">删除</button>
        <button :disabled="!selectedId || isExternal" @click="selectedId && api.openTileWindow(selectedId)">
          钉到屏幕
        </button>
        <select v-model="activeCategory" @change="moveSelected(($event.target as HTMLSelectElement).value)">
          <option value="">未分类</option>
          <option v-for="category in categories" :key="category" :value="category">{{ category }}</option>
        </select>
        <button v-if="isTodoNote" class="todo-toolbar-add" @click="addTodoItem()">新增待办</button>
        <div v-if="!isTodoNote" class="format-buttons">
          <button v-for="[action, label, tip] in toolbar" :key="action" :title="tip" @click="applyFormat(action)">
            {{ label }}
          </button>
        </div>
        <div v-if="!isTodoNote" class="segmented mode-tabs">
          <button
            v-for="mode in (['edit', 'split', 'preview'] as ViewMode[])"
            :key="mode"
            :class="{ active: viewMode === mode }"
            @click="viewMode = mode"
          >
            {{ mode === "edit" ? "编辑" : mode === "split" ? "分栏" : "预览" }}
          </button>
        </div>
      </div>
      <div class="editor-meta">
        <input
          v-model="title"
          :disabled="!selectedId"
          placeholder="无标题笔记"
          @input="saveState = 'dirty'"
        />
        <span>
          {{
            selectedExternal
              ? `外部文件 · ${selectedExternal.filePath}`
              : selectedNote
                ? `${formatShortDate(selectedNote.updatedAt)} ${formatTime(selectedNote.updatedAt)}`
                : "选择或新建一篇笔记"
          }}
        </span>
        <span>{{ countChars(content) }} 字</span>
        <span :class="['save-state', saveState]">{{ saveState }}</span>
      </div>
      <div v-if="isTodoNote" class="todo-workspace">
        <div class="todo-list-editor">
          <label
            v-for="(item, index) in todoItems"
            :key="index"
            :class="['todo-row', item.done ? 'done' : '']"
          >
            <input type="checkbox" :checked="item.done" @change="toggleTodoItem(index)" />
            <input
              :data-todo-index="index"
              :value="item.text"
              placeholder="输入待办事项"
              @input="updateTodoText(index, ($event.target as HTMLInputElement).value)"
              @keydown="handleTodoKeydown($event, index)"
            />
            <button title="删除待办" @click.prevent="removeTodoItem(index)">×</button>
          </label>
        </div>
      </div>
      <div v-else :class="['workspace', viewMode]">
        <textarea
          v-if="viewMode === 'edit' || viewMode === 'split'"
          ref="textRef"
          v-model="content"
          :disabled="!selectedId"
          :style="{ fontSize: `${config.fontSize}px`, tabSize: config.tabIndentSize }"
          placeholder="开始写作……"
          @input="saveState = 'dirty'"
          @keydown="handleEditorKeydown"
        />
        <div v-if="viewMode === 'preview' || viewMode === 'split'" class="preview-pane">
          <MarkdownPreview
            :content="content"
            :font-size="config.fontSize"
            :render-html="config.renderHtmlMarkdown"
            @toggle-task="toggleTask"
          />
        </div>
      </div>
      <footer class="statusbar">
        <span>{{ isTodoNote ? `${todoItems.length} 项待办` : `Ln ${content.split("\n").length}` }}</span>
        <span>{{ isTodoNote ? "Todo" : "Markdown + LaTeX" }}</span>
        <span>UTF-8</span>
        <span>{{ contentKb(content) }} KB</span>
      </footer>
    </main>
    <SettingsPanel v-if="settingsOpen" :config="config" @change="saveSettings" @close="settingsOpen = false" />
  </div>

  <div v-else-if="isPad && config" class="pad-shell">
    <header data-drag-region>
      <div>
        <button :class="{ active: !openList }" @click="openList = false">{{ editingId ? "编辑" : "新建" }}</button>
        <button :class="{ active: openList }" @click="openList = true">打开</button>
      </div>
      <div>
        <button :disabled="!editingId" @click="editingId && api.openTileWindow(editingId)">📌</button>
        <button @click="appWindow.close()">×</button>
      </div>
    </header>
    <div v-if="openList" class="pad-list">
      <button v-for="note in notes" :key="note.id" @click="openPadNote(note.id)">
        <strong>{{ noteTitle(note) }}</strong>
        <span>{{ note.preview || "空白笔记" }}</span>
      </button>
    </div>
    <div v-else class="pad-editor">
      <input
        v-model="title"
        placeholder="标题（可选）"
        :style="{ fontSize: `${config.surfaceFontSize}px` }"
        @input="status = '未保存'"
      />
      <textarea
        v-model="content"
        placeholder="写点什么……"
        :style="{ fontSize: `${config.surfaceFontSize}px`, tabSize: config.tabIndentSize }"
        @input="status = '未保存'"
      />
      <footer>
        <span>{{ countChars(content) }} 字 · {{ status }}</span>
        <button @click="clearPad">清空</button>
        <button @click="savePad">保存</button>
      </footer>
    </div>
  </div>

  <Tile
    v-else-if="isTile && tileNote && config"
    :title="tileNote.title"
    :content="tileNote.content"
    :color="config.tileColorMode === 'custom' ? config.tileColor : '#f8f5ec'"
    :font-size="config.surfaceFontSize"
    :render-markdown="config.tileRenderMarkdown"
    :editing="tileEditing"
    :fixed="tileFixed"
    @copy="copyTileContent"
    @save="saveTileNote"
    @toggle-fixed="toggleTileFixed"
    @toggle-edit="tileEditing = !tileEditing"
    @update-title="updateTileTitle"
    @update-content="updateTileContent"
  />
</template>
