// src/SettingsPanel.vue
<script setup lang="ts">
import { chooseNotesDirectory } from "./api";
import type { AppConfig, ThemeOption, ViewMode } from "./types";

const props = defineProps<{
  config: AppConfig;
}>();

const emit = defineEmits<{
  change: [config: AppConfig];
  close: [];
}>();

function set<K extends keyof AppConfig>(key: K, value: AppConfig[K]) {
  emit("change", { ...props.config, [key]: value });
}

async function chooseDir() {
  const dir = await chooseNotesDirectory();
  if (dir) set("notesDir", dir);
}
</script>

<template>
  <aside class="settings-panel">
    <header>
      <h2>应用设置</h2>
      <button @click="$emit('close')">×</button>
    </header>
    <section>
      <label>主题</label>
      <div class="segmented">
        <button
          v-for="theme in (['light', 'dark', 'system'] as ThemeOption[])"
          :key="theme"
          :class="{ active: config.theme === theme }"
          @click="set('theme', theme)"
        >
          {{ theme === "light" ? "浅色" : theme === "dark" ? "深色" : "跟随系统" }}
        </button>
      </div>
    </section>
    <section>
      <label>笔记目录</label>
      <div class="path-row">
        <input :value="config.notesDir" readonly />
        <button @click="chooseDir">选择</button>
      </div>
    </section>
    <section class="settings-grid">
      <label class="toggle-row"><span>关闭到托盘</span><input type="checkbox" :checked="config.closeToTray" @change="set('closeToTray', ($event.target as HTMLInputElement).checked)" /></label>
      <label class="toggle-row"><span>开机自启</span><input type="checkbox" :checked="config.autostart" @change="set('autostart', ($event.target as HTMLInputElement).checked)" /></label>
      <label class="toggle-row"><span>自动保存笔记</span><input type="checkbox" :checked="config.noteAutoSave" @change="set('noteAutoSave', ($event.target as HTMLInputElement).checked)" /></label>
      <label class="toggle-row"><span>小窗笔记自动保存</span><input type="checkbox" :checked="config.noteSurfaceAutoSave" @change="set('noteSurfaceAutoSave', ($event.target as HTMLInputElement).checked)" /></label>
      <label class="toggle-row"><span>外部文件自动保存</span><input type="checkbox" :checked="config.externalFileAutoSave" @change="set('externalFileAutoSave', ($event.target as HTMLInputElement).checked)" /></label>
      <label class="toggle-row"><span>磁贴渲染 Markdown</span><input type="checkbox" :checked="config.tileRenderMarkdown" @change="set('tileRenderMarkdown', ($event.target as HTMLInputElement).checked)" /></label>
      <label class="toggle-row"><span>允许 HTML 标签渲染</span><input type="checkbox" :checked="config.renderHtmlMarkdown" @change="set('renderHtmlMarkdown', ($event.target as HTMLInputElement).checked)" /></label>
      <label class="toggle-row"><span>快捷键打开时跟随鼠标位置</span><input type="checkbox" :checked="config.openAtCursor" @change="set('openAtCursor', ($event.target as HTMLInputElement).checked)" /></label>
    </section>
    <section>
      <label>默认视图</label>
      <div class="segmented">
        <button
          v-for="mode in (['edit', 'split', 'preview'] as ViewMode[])"
          :key="mode"
          :class="{ active: config.defaultViewMode === mode }"
          @click="set('defaultViewMode', mode)"
        >
          {{ mode === "edit" ? "编辑" : mode === "split" ? "分栏" : "预览" }}
        </button>
      </div>
    </section>
    <section>
      <label>快捷键</label>
      <input :value="config.globalShortcut" placeholder="Ctrl+Space" @input="set('globalShortcut', ($event.target as HTMLInputElement).value)" />
      <input :value="config.toggleVisibilityShortcut" placeholder="Ctrl+Alt+N" @input="set('toggleVisibilityShortcut', ($event.target as HTMLInputElement).value)" />
    </section>
    <section>
      <label class="range-row"><span>编辑器字号</span><input type="range" min="8" max="30" :value="config.fontSize" @input="set('fontSize', Number(($event.target as HTMLInputElement).value))" /><b>{{ config.fontSize }}px</b></label>
      <label class="range-row"><span>小窗/磁贴字号</span><input type="range" min="8" max="30" :value="config.surfaceFontSize" @input="set('surfaceFontSize', Number(($event.target as HTMLInputElement).value))" /><b>{{ config.surfaceFontSize }}px</b></label>
      <label class="range-row"><span>Tab 缩进</span><input type="range" min="1" max="8" :value="config.tabIndentSize" @input="set('tabIndentSize', Number(($event.target as HTMLInputElement).value))" /><b>{{ config.tabIndentSize }}</b></label>
    </section>
    <section>
      <label>磁贴颜色</label>
      <div class="color-row">
        <select :value="config.tileColorMode" @change="set('tileColorMode', ($event.target as HTMLSelectElement).value as 'system' | 'custom')">
          <option value="system">跟随主题</option>
          <option value="custom">自定义</option>
        </select>
        <input type="color" :value="config.tileColor" @input="set('tileColor', ($event.target as HTMLInputElement).value)" />
        <input :value="config.tileColor" @input="set('tileColor', ($event.target as HTMLInputElement).value)" />
      </div>
    </section>
    <section>
      <label>背景图片</label>
      <input :value="config.backgroundImagePath ?? ''" placeholder="图片路径" @input="set('backgroundImagePath', ($event.target as HTMLInputElement).value)" />
      <div class="segmented">
        <button
          v-for="fit in (['cover', 'contain', 'repeat'] as const)"
          :key="fit"
          :class="{ active: config.backgroundFit === fit }"
          @click="set('backgroundFit', fit)"
        >
          {{ fit === "cover" ? "填充" : fit === "contain" ? "完整" : "平铺" }}
        </button>
      </div>
      <label class="range-row"><span>遮罩</span><input type="range" min="0" max="100" :value="Math.round(config.backgroundDim * 100)" @input="set('backgroundDim', Number(($event.target as HTMLInputElement).value) / 100)" /><b>{{ Math.round(config.backgroundDim * 100) }}%</b></label>
      <label class="range-row"><span>模糊</span><input type="range" min="0" max="20" :value="config.backgroundBlur" @input="set('backgroundBlur', Number(($event.target as HTMLInputElement).value))" /><b>{{ config.backgroundBlur }}px</b></label>
      <label class="range-row"><span>缩放</span><input type="range" min="50" max="200" :value="Math.round(config.backgroundScale * 100)" @input="set('backgroundScale', Number(($event.target as HTMLInputElement).value) / 100)" /><b>{{ Math.round(config.backgroundScale * 100) }}%</b></label>
    </section>
  </aside>
</template>

// src/SettingsPanel.tsx
import { chooseNotesDirectory } from "./api";
import type { AppConfig, ThemeOption, ViewMode } from "./types";

function Toggle({
  label,
  checked,
  onChange,
}: {
  label: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
}) {
  return (
    <label className="toggle-row">
      <span>{label}</span>
      <input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} />
    </label>
  );
}

function Range({
  label,
  value,
  min,
  max,
  step = 1,
  suffix = "",
  onChange,
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  step?: number;
  suffix?: string;
  onChange: (value: number) => void;
}) {
  return (
    <label className="range-row">
      <span>{label}</span>
      <input
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={(event) => onChange(Number(event.target.value))}
      />
      <b>
        {value}
        {suffix}
      </b>
    </label>
  );
}

export function SettingsPanel({
  config,
  onChange,
  onClose,
}: {
  config: AppConfig;
  onChange: (config: AppConfig) => void;
  onClose: () => void;
}) {
  const set = <K extends keyof AppConfig>(key: K, value: AppConfig[K]) =>
    onChange({ ...config, [key]: value });

  return (
    <aside className="settings-panel">
      <header>
        <h2>应用设置</h2>
        <button onClick={onClose}>×</button>
      </header>
      <section>
        <label>主题</label>
        <div className="segmented">
          {(["light", "dark", "system"] as ThemeOption[]).map((theme) => (
            <button
              key={theme}
              className={config.theme === theme ? "active" : ""}
              onClick={() => set("theme", theme)}
            >
              {theme === "light" ? "浅色" : theme === "dark" ? "深色" : "跟随系统"}
            </button>
          ))}
        </div>
      </section>
      <section>
        <label>笔记目录</label>
        <div className="path-row">
          <input value={config.notesDir} readOnly />
          <button
            onClick={async () => {
              const dir = await chooseNotesDirectory();
              if (dir) set("notesDir", dir);
            }}
          >
            选择
          </button>
        </div>
      </section>
      <section className="settings-grid">
        <Toggle label="关闭到托盘" checked={config.closeToTray} onChange={(v) => set("closeToTray", v)} />
        <Toggle label="开机自启" checked={config.autostart} onChange={(v) => set("autostart", v)} />
        <Toggle label="自动保存笔记" checked={config.noteAutoSave} onChange={(v) => set("noteAutoSave", v)} />
        <Toggle
          label="小窗笔记自动保存"
          checked={config.noteSurfaceAutoSave}
          onChange={(v) => set("noteSurfaceAutoSave", v)}
        />
        <Toggle
          label="外部文件自动保存"
          checked={config.externalFileAutoSave}
          onChange={(v) => set("externalFileAutoSave", v)}
        />
        <Toggle
          label="磁贴渲染 Markdown"
          checked={config.tileRenderMarkdown}
          onChange={(v) => set("tileRenderMarkdown", v)}
        />
        <Toggle
          label="允许 HTML 标签渲染"
          checked={config.renderHtmlMarkdown}
          onChange={(v) => set("renderHtmlMarkdown", v)}
        />
        <Toggle
          label="快捷键打开时跟随鼠标位置"
          checked={config.openAtCursor}
          onChange={(v) => set("openAtCursor", v)}
        />
      </section>
      <section>
        <label>默认视图</label>
        <div className="segmented">
          {(["edit", "split", "preview"] as ViewMode[]).map((mode) => (
            <button
              key={mode}
              className={config.defaultViewMode === mode ? "active" : ""}
              onClick={() => set("defaultViewMode", mode)}
            >
              {mode === "edit" ? "编辑" : mode === "split" ? "分栏" : "预览"}
            </button>
          ))}
        </div>
      </section>
      <section>
        <label>快捷键</label>
        <input
          value={config.globalShortcut}
          onChange={(event) => set("globalShortcut", event.target.value)}
          placeholder="Ctrl+Space"
        />
        <input
          value={config.toggleVisibilityShortcut}
          onChange={(event) => set("toggleVisibilityShortcut", event.target.value)}
          placeholder="Ctrl+Alt+N"
        />
      </section>
      <section>
        <Range label="编辑器字号" value={config.fontSize} min={8} max={30} suffix="px" onChange={(v) => set("fontSize", v)} />
        <Range
          label="小窗/磁贴字号"
          value={config.surfaceFontSize}
          min={8}
          max={30}
          suffix="px"
          onChange={(v) => set("surfaceFontSize", v)}
        />
        <Range label="Tab 缩进" value={config.tabIndentSize} min={1} max={8} onChange={(v) => set("tabIndentSize", v)} />
      </section>
      <section>
        <label>磁贴颜色</label>
        <div className="color-row">
          <select value={config.tileColorMode} onChange={(event) => set("tileColorMode", event.target.value as "system" | "custom")}>
            <option value="system">跟随主题</option>
            <option value="custom">自定义</option>
          </select>
          <input type="color" value={config.tileColor} onChange={(event) => set("tileColor", event.target.value)} />
          <input value={config.tileColor} onChange={(event) => set("tileColor", event.target.value)} />
        </div>
      </section>
      <section>
        <label>背景图片</label>
        <input
          value={config.backgroundImagePath ?? ""}
          onChange={(event) => set("backgroundImagePath", event.target.value)}
          placeholder="图片路径"
        />
        <div className="segmented">
          {(["cover", "contain", "repeat"] as const).map((fit) => (
            <button
              key={fit}
              className={config.backgroundFit === fit ? "active" : ""}
              onClick={() => set("backgroundFit", fit)}
            >
              {fit === "cover" ? "填充" : fit === "contain" ? "完整" : "平铺"}
            </button>
          ))}
        </div>
        <Range label="遮罩" value={Math.round(config.backgroundDim * 100)} min={0} max={100} suffix="%" onChange={(v) => set("backgroundDim", v / 100)} />
        <Range label="模糊" value={config.backgroundBlur} min={0} max={20} suffix="px" onChange={(v) => set("backgroundBlur", v)} />
        <Range label="缩放" value={Math.round(config.backgroundScale * 100)} min={50} max={200} suffix="%" onChange={(v) => set("backgroundScale", v / 100)} />
      </section>
    </aside>
  );
}
