// src/Tile.tsx
import { MarkdownPreview } from "./MarkdownPreview";

export function Tile({
  title,
  content,
  color,
  fontSize,
  renderMarkdown,
  onClose,
  onEdit,
  onCopy,
}: {
  title: string;
  content: string;
  color: string;
  fontSize: number;
  renderMarkdown: boolean;
  onClose: () => void;
  onEdit?: () => void;
  onCopy?: () => void;
}) {
  return (
    <div className="tile" style={{ background: color }}>
      <div className="tile-header" data-tauri-drag-region>
        <strong>{title || "无标题笔记"}</strong>
        <div className="tile-actions">
          {onCopy && (
            <button title="复制" onClick={onCopy}>
              ⧉
            </button>
          )}
          {onEdit && (
            <button title="编辑" onClick={onEdit}>
              ✎
            </button>
          )}
          <button title="取消钉屏" onClick={onClose}>
            ×
          </button>
        </div>
      </div>
      <div className="tile-body" style={{ fontSize }}>
        {renderMarkdown ? (
          <MarkdownPreview content={content} fontSize={fontSize} renderHtml={false} />
        ) : (
          <pre>{content}</pre>
        )}
      </div>
    </div>
  );
}

// src/Tile.vue
<script setup lang="ts">
import MarkdownPreview from "./MarkdownPreview.vue";

defineProps<{
  title: string;
  content: string;
  color: string;
  fontSize: number;
  renderMarkdown: boolean;
}>();

defineEmits<{
  copy: [];
  edit: [];
  close: [];
}>();
</script>

<template>
  <div class="tile" :style="{ background: color }">
    <div class="tile-header" data-drag-region>
      <strong>{{ title || "无标题笔记" }}</strong>
      <div class="tile-actions">
        <button title="复制" @click="$emit('copy')">⧉</button>
        <button title="编辑" @click="$emit('edit')">✎</button>
        <button title="取消钉屏" @click="$emit('close')">×</button>
      </div>
    </div>
    <div class="tile-body" :style="{ fontSize: `${fontSize}px` }">
      <MarkdownPreview v-if="renderMarkdown" :content="content" :font-size="fontSize" :render-html="false" />
      <pre v-else>{{ content }}</pre>
    </div>
  </div>
</template>
